<x-layouts::app :title="$attempt->activity->titulo"><div class="p-4 sm:p-6"><div class="mx-auto max-w-4xl space-y-6">
    <div><p class="text-sm font-semibold text-cyan-600">Intento {{ $attempt->attempt_number }}</p><h1 class="text-2xl font-bold dark:text-white">{{ $attempt->activity->titulo }}</h1><p class="text-zinc-500">Selecciona HAY, AHÍ o AY en cada espacio.</p></div>
    <div class="grid gap-3 sm:grid-cols-3"><div class="rounded-lg bg-cyan-50 p-4 text-sm text-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-100"><strong>HAY:</strong> indica existencia.</div><div class="rounded-lg bg-cyan-50 p-4 text-sm text-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-100"><strong>AHÍ:</strong> indica un lugar.</div><div class="rounded-lg bg-cyan-50 p-4 text-sm text-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-100"><strong>AY:</strong> expresa emoción o dolor.</div></div>
    @if ($errors->any())<div class="rounded-lg border border-red-300 bg-red-100 p-4 text-red-800"><ul class="list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('activities.hay-ahi-ay.attempts.submit', $attempt) }}" class="space-y-5">@csrf
        <ol class="space-y-3">@foreach ($display as $item)@php [$before, $after] = array_pad(explode('___', $item['sentence'], 2), 2, ''); @endphp<li class="rounded-xl border bg-white p-4 text-lg leading-relaxed dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200"><span class="mr-2 text-sm font-bold text-cyan-600">{{ $loop->iteration }}.</span>{{ $before }} <label for="answer-{{ $item['id'] }}" class="sr-only">Respuesta de la oración {{ $loop->iteration }}</label><select id="answer-{{ $item['id'] }}" name="answers[{{ $item['id'] }}]" required class="mx-1 rounded-lg border-2 border-cyan-400 bg-cyan-50 px-3 py-1 font-bold text-cyan-900 dark:bg-cyan-950 dark:text-cyan-100"><option value="">---</option>@foreach ($attempt->answers['options'] as $option)<option value="{{ $option }}" @selected(old('answers.'.$item['id']) === $option)>{{ mb_strtoupper($option) }}</option>@endforeach</select> {{ $after }}</li>@endforeach</ol>
        <div class="flex justify-end"><button class="rounded-lg bg-cyan-600 px-6 py-3 text-lg font-bold text-white">Enviar respuestas</button></div>
    </form>
</div></div></x-layouts::app>
