<x-layouts::app :title="__('Calificar entrega')">
    <div class="p-6"><div class="mx-auto max-w-4xl space-y-6">
        <div><p class="text-sm font-semibold text-blue-600">{{ $submission->activity->teachingAssignment->subject->nombre_materia }}</p><h1 class="text-2xl font-bold dark:text-white">Calificar: {{ $submission->activity->titulo }}</h1><p class="text-zinc-500">Estudiante: {{ $submission->student->name }}</p></div>
        <div class="space-y-3 rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200"><p><strong>Estado:</strong> {{ str_replace('_', ' ', ucfirst($submission->estado)) }}</p><p><strong>Fecha:</strong> {{ $submission->fecha_entrega?->format('d/m/Y H:i') ?? 'Borrador' }}</p><p class="whitespace-pre-line"><strong>Respuesta:</strong><br>{{ $submission->respuesta ?: 'Sin respuesta escrita.' }}</p>@if ($submission->archivo_path)<a href="{{ route('submissions.download', $submission) }}" class="text-sky-600">Descargar archivo entregado</a>@endif</div>
        <form method="POST" action="{{ route('submissions.update-grade', $submission) }}" class="space-y-5 rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-900">@csrf @method('PUT')
            <div><label for="calificacion" class="mb-1 block text-sm font-medium dark:text-zinc-300">Calificación (máximo {{ $submission->activity->puntaje_maximo }})</label><input id="calificacion" name="calificacion" type="number" min="0" max="{{ $submission->activity->puntaje_maximo }}" step="0.01" value="{{ old('calificacion', $submission->calificacion) }}" required class="w-full rounded-lg border border-zinc-300 px-3 py-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('calificacion')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="retroalimentacion" class="mb-1 block text-sm font-medium dark:text-zinc-300">Retroalimentación</label><textarea id="retroalimentacion" name="retroalimentacion" rows="6" class="w-full rounded-lg border border-zinc-300 px-3 py-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">{{ old('retroalimentacion', $submission->retroalimentacion) }}</textarea>@error('retroalimentacion')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div class="flex justify-end gap-3"><a href="{{ route('submissions.show', $submission) }}" class="rounded-lg border px-4 py-2 dark:text-white">Cancelar</a><button class="rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white">Guardar calificación</button></div>
        </form>
    </div></div>
</x-layouts::app>
