<x-layouts::app :title="__('Entregas y calificaciones')">
    <div class="p-6"><div class="mx-auto max-w-7xl space-y-6">
        <div><h1 class="text-2xl font-bold dark:text-white">@role('estudiante') Mis entregas @else Entregas y calificaciones @endrole</h1><p class="text-sm text-zinc-500">Consulta el progreso, las entregas y sus calificaciones.</p></div>
        @if (session('success'))<div class="rounded-lg border border-green-300 bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        <div class="overflow-x-auto rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><table class="w-full text-left text-sm"><thead class="bg-zinc-100 dark:bg-zinc-800"><tr>@unlessrole('estudiante')<th class="px-4 py-3">Estudiante</th>@endunlessrole<th class="px-4 py-3">Actividad</th><th class="px-4 py-3">Materia y grupo</th><th class="px-4 py-3">Entrega</th><th class="px-4 py-3">Estado</th><th class="px-4 py-3">Calificación</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">
            @forelse ($submissions as $submission)@php $hideInteractiveGrade = auth()->user()->hasRole('estudiante') && $submission->activity->tipo === 'relacion_columnas' && ! ($submission->activity->content?->configuracion['show_result_immediately'] ?? false); @endphp<tr class="dark:text-zinc-300">@unlessrole('estudiante')<td class="px-4 py-3 font-semibold">{{ $submission->student->name }}</td>@endunlessrole<td class="px-4 py-3">{{ $submission->activity->titulo }}</td><td class="px-4 py-3">{{ $submission->activity->teachingAssignment->subject->nombre_materia }} — {{ $submission->activity->teachingAssignment->schoolGroup->schoolGrade?->nombre_grado }} {{ $submission->activity->teachingAssignment->schoolGroup->nombre_grupo }}</td><td class="px-4 py-3">{{ $submission->fecha_entrega?->format('d/m/Y H:i') ?? 'Borrador' }}</td><td class="px-4 py-3">{{ str_replace('_', ' ', ucfirst($submission->estado)) }}</td><td class="px-4 py-3">{{ ! $hideInteractiveGrade && $submission->calificacion !== null ? $submission->calificacion.' / '.$submission->activity->puntaje_maximo : 'Pendiente' }}</td><td class="px-4 py-3"><div class="flex justify-end gap-3"><a href="{{ route('submissions.show', $submission) }}" class="text-sky-600">Ver</a>@can('update', $submission)<a href="{{ route('submissions.edit', $submission) }}" class="text-amber-600">Editar</a>@endcan @can('grade', $submission)<a href="{{ route('submissions.grade', $submission) }}" class="text-violet-600">Calificar</a>@endcan</div></td></tr>
            @empty<tr><td colspan="7" class="px-4 py-8 text-center text-zinc-500">No hay entregas registradas.</td></tr>@endforelse
        </tbody></table></div>{{ $submissions->links() }}
    </div></div>
</x-layouts::app>
