<x-layouts::app :title="__('Detalle de entrega')">
    <div class="p-6"><div class="mx-auto max-w-5xl space-y-6">
        @if (session('success'))<div class="rounded-lg border border-green-300 bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-blue-600">{{ $submission->activity->teachingAssignment->subject->nombre_materia }}</p><h1 class="text-2xl font-bold dark:text-white">{{ $submission->activity->titulo }}</h1><p class="text-zinc-500">Entrega de {{ $submission->student->name }}</p></div><div class="flex gap-2"><a href="{{ route('submissions.index') }}" class="rounded-lg border px-4 py-2 dark:text-white">Regresar</a>@can('grade', $submission)<a href="{{ route('submissions.grade', $submission) }}" class="rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white">Calificar</a>@endcan</div></div>
        @php $hideInteractiveGrade = auth()->user()->hasRole('estudiante') && $submission->activity->tipo === 'relacion_columnas' && ! ($submission->activity->content?->configuracion['show_result_immediately'] ?? false); @endphp
        <div class="grid gap-5 md:grid-cols-4"><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Estado</p><p class="font-semibold dark:text-white">{{ str_replace('_', ' ', ucfirst($submission->estado)) }}</p></div><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Fecha de entrega</p><p class="font-semibold dark:text-white">{{ $submission->fecha_entrega?->format('d/m/Y H:i') ?? 'Borrador' }}</p></div><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Calificación</p><p class="font-semibold dark:text-white">{{ ! $hideInteractiveGrade && $submission->calificacion !== null ? $submission->calificacion.' / '.$submission->activity->puntaje_maximo : 'Pendiente' }}</p></div><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Calificó</p><p class="font-semibold dark:text-white">{{ $hideInteractiveGrade ? 'Pendiente' : ($submission->grader?->name ?? 'Automática') }}</p></div></div>
        <div class="space-y-5 rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200"><section><h2 class="font-bold">Respuesta</h2><p class="whitespace-pre-line">{{ $submission->respuesta ?: 'Sin respuesta escrita.' }}</p></section>@if ($submission->archivo_path)<a href="{{ route('submissions.download', $submission) }}" class="inline-flex rounded-lg bg-sky-100 px-4 py-2 font-semibold text-sky-700">Descargar {{ basename($submission->archivo_path) }}</a>@endif @if ($submission->retroalimentacion && ! $hideInteractiveGrade)<section><h2 class="font-bold">Retroalimentación</h2><p class="whitespace-pre-line">{{ $submission->retroalimentacion }}</p></section>@endif</div>
        @can('update', $submission)<div class="flex gap-3"><a href="{{ route('submissions.edit', $submission) }}" class="rounded-lg bg-amber-500 px-4 py-2 font-semibold text-white">Editar entrega</a><form method="POST" action="{{ route('submissions.destroy', $submission) }}" onsubmit="return confirm('¿Deseas eliminar esta entrega?')">@csrf @method('DELETE')<button class="rounded-lg bg-red-600 px-4 py-2 font-semibold text-white">Eliminar</button></form></div>@endcan
    </div></div>
</x-layouts::app>
