<x-layouts::app :title="$activity->titulo">
    <div class="p-6"><div class="mx-auto max-w-6xl space-y-6">
        @if (session('success'))<div class="rounded-lg border border-green-300 bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-blue-600">{{ $activity->teachingAssignment->subject->nombre_materia }}</p><h1 class="text-2xl font-bold dark:text-white">{{ $activity->titulo }}</h1><p class="text-zinc-500">{{ $activity->teachingAssignment->schoolGroup->schoolGrade?->nombre_grado }} — Grupo {{ $activity->teachingAssignment->schoolGroup->nombre_grupo }}</p></div><div class="flex gap-2"><a href="{{ route('activities.index') }}" class="rounded-lg border px-4 py-2 dark:text-white">Regresar</a>@can('update', $activity)<a href="{{ route('activities.edit', $activity) }}" class="rounded-lg bg-amber-500 px-4 py-2 font-semibold text-white">Editar</a>@endcan</div></div>
        <div class="grid gap-5 md:grid-cols-4"><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Docente</p><p class="font-semibold dark:text-white">{{ $activity->teachingAssignment->teacher->name }}</p></div><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Fecha límite</p><p class="font-semibold dark:text-white">{{ $activity->fecha_limite?->format('d/m/Y H:i') ?? 'Sin límite' }}</p></div><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Puntaje</p><p class="font-semibold dark:text-white">{{ $activity->puntaje_maximo }}</p></div><div class="rounded-xl border p-4 dark:border-zinc-700"><p class="text-sm text-zinc-500">Estado</p><p class="font-semibold dark:text-white">{{ ucfirst($activity->estado) }}</p></div></div>
        <div class="space-y-4 rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200">@if ($activity->descripcion)<section><h2 class="font-bold">Descripción</h2><p class="whitespace-pre-line">{{ $activity->descripcion }}</p></section>@endif @if ($activity->instrucciones)<section><h2 class="font-bold">Instrucciones</h2><p class="whitespace-pre-line">{{ $activity->instrucciones }}</p></section>@endif @if ($activity->archivo_path)<a href="{{ route('activities.download', $activity) }}" class="inline-flex rounded-lg bg-sky-100 px-4 py-2 font-semibold text-sky-700">Descargar {{ basename($activity->archivo_path) }}</a>@endif</div>
        @role('estudiante')
            @if ($activity->tipo === 'relacion_columnas')
                <div class="rounded-xl border border-blue-200 bg-blue-50 p-5 dark:border-blue-900 dark:bg-blue-950/30"><h2 class="mb-2 text-lg font-bold text-blue-900 dark:text-blue-100">Actividad interactiva</h2><p class="mb-4 text-blue-700 dark:text-blue-300">Relaciona los elementos de ambas columnas y recibe una puntuación automática.</p><a href="{{ route('activities.play', $activity) }}" class="inline-block rounded-lg bg-blue-600 px-5 py-3 font-bold text-white">Jugar ahora</a></div>
            @elseif ($activity->tipo === 'sopa_letras')
                <div class="rounded-xl border border-violet-200 bg-violet-50 p-5 dark:border-violet-900 dark:bg-violet-950/30"><h2 class="mb-2 text-lg font-bold text-violet-900 dark:text-violet-100">Sopa de letras</h2><p class="mb-4 text-violet-700 dark:text-violet-300">Encuentra las palabras ocultas y recibe una puntuación automática.</p><a href="{{ route('activities.word-search.play', $activity) }}" class="inline-block rounded-lg bg-violet-600 px-5 py-3 font-bold text-white">Jugar ahora</a></div>
            @else
                <div class="rounded-xl border border-zinc-200 p-5 dark:border-zinc-700"><h2 class="mb-3 text-lg font-bold dark:text-white">Mi entrega</h2>@if ($submission)<p class="dark:text-zinc-300">Estado: {{ str_replace('_', ' ', ucfirst($submission->estado)) }}</p><a href="{{ route('submissions.show', $submission) }}" class="mt-3 inline-block rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Ver entrega</a>@if ($submission->estado !== 'revisada')<a href="{{ route('submissions.edit', $submission) }}" class="mt-3 inline-block rounded-lg bg-amber-500 px-4 py-2 font-semibold text-white">Editar entrega</a>@endif @else <a href="{{ route('submissions.create', ['activity_id' => $activity]) }}" class="rounded-lg bg-green-600 px-4 py-2 font-semibold text-white">Realizar entrega</a>@endif</div>
            @endif
        @else
            @if ($activity->tipo === 'relacion_columnas')<a href="{{ route('activities.attempts.index', $activity) }}" class="inline-flex rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white">Ver intentos y resultados</a>@elseif ($activity->tipo === 'sopa_letras')<a href="{{ route('activities.word-search.attempts.index', $activity) }}" class="inline-flex rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white">Ver intentos y resultados</a>@endif
            <div class="rounded-xl border border-zinc-200 dark:border-zinc-700"><h2 class="p-5 text-lg font-bold dark:text-white">Entregas ({{ $activity->submissions->count() }})</h2><div class="divide-y dark:divide-zinc-700">@forelse ($activity->submissions as $item)<div class="flex items-center justify-between gap-4 p-4 dark:text-zinc-300"><div><p class="font-semibold">{{ $item->student->name }}</p><p class="text-sm text-zinc-500">{{ str_replace('_', ' ', ucfirst($item->estado)) }} — {{ $item->fecha_entrega?->format('d/m/Y H:i') ?? 'Borrador' }}</p></div><div class="flex gap-3"><a href="{{ route('submissions.show', $item) }}" class="text-sky-600">Ver</a>@can('grade', $item)<a href="{{ route('submissions.grade', $item) }}" class="text-violet-600">Calificar</a>@endcan</div></div>@empty<p class="p-5 text-zinc-500">Aún no hay entregas.</p>@endforelse</div></div>
        @endrole
    </div></div>
</x-layouts::app>
